# Generated by Django 4.0.2 on 2022-02-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_employee_city_employee_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='expected_salary',
            new_name='salary',
        ),
    ]
